---
# install packages common to all machines

- name: Install SELinux python package needed by ansible
  become: yes
  yum: name={{ item }} state=present
  with_items:
    - epel-release
    - libselinux-python
    - python-passlib
