---
# Install Elasticsearch

- name: Import the Elasticsearch public GPG key into rpm
  become: yes
  rpm_key: state=present key=https://packages.elastic.co/GPG-KEY-elasticsearch #owner=root group=root

- name: Create a yum repository for Elasticsearch
  become: yes
  template: src=elastic.repo.j2 dest=/etc/yum.repos.d/elasticsearch.repo     #mode=0644 owner=root owner=root

- name: Install Elasticsearch package
  become: yes
  yum: name=elasticsearch state=present

- name: Configure Elasticsearch - disable dynamic scripts
  become: yes
  lineinfile: "dest=/etc/elasticsearch/elasticsearch.yml line='script.disable_dynamic: true' state=present"

- name: Configure Elasticsearch - Restrict outside access to instance
  become: yes
  lineinfile: "dest=/etc/elasticsearch/elasticsearch.yml regexp='# discovery.zen.ping.multicast.enabled: false' insertafter='# discovery.zen.ping.multicast.enabled: false' line='discovery.zen.ping.multicast.enabled: false' state=present"

- name: Configure Elasticsearch - Restrict outside access
  become: yes
  lineinfile: "dest=/etc/elasticsearch/elasticsearch.yml regexp='# network.host: 192.168.0.1' insertafter='# network.host: 192.168.0.1' line='network.host: localhost'"

- name: Start Elasticsearch and enable on boot
  become: yes
  service: name=elasticsearch state=started enabled=yes
